"""Updated magazines and plans  models

Revision ID: 1fa85d43f513
Revises: d5fae22c4211
Create Date: 2024-10-09 01:33:11.347101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa85d43f513'
down_revision: Union[str, None] = 'd5fae22c4211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_plans_id', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_magazines_id', table_name='magazines')
    op.drop_index('ix_magazines_name', table_name='magazines')
    op.drop_table('magazines')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('magazines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('base_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='magazines_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_magazines_name', 'magazines', ['name'], unique=False)
    op.create_index('ix_magazines_id', 'magazines', ['id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('plans_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('renewal_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('magazine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines.id'], name='plans_magazine_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='plans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_plans_id', 'plans', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('magazine_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('renewal_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['magazine_id'], ['magazines.id'], name='subscriptions_magazine_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='subscriptions_plan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###
