"""Update models with correct table names and relationships

Revision ID: 2db52bde14e8
Revises: 17c561223982
Create Date: 2024-08-12 16:00:34.326384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2db52bde14e8'
down_revision: Union[str, None] = '17c561223982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'magazine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('subscriptions', 'renewal_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('subscriptions', 'renewal_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('subscriptions', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'magazine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
